"""
main.py — FastAPI backend for the AI Portfolio Chatbot.

Endpoints:
  GET  /        → Health check / welcome route
  POST /chat    → Accepts a user message and returns a chatbot response
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from chatbot import get_response

# Initialize FastAPI app
app = FastAPI(
    title="Portfolio Chatbot API",
    description="A simple AI chatbot API for the developer portfolio.",
    version="1.0.0",
)

# Allow requests from the React frontend (running on localhost:5173 in dev)
# In production, replace the origins list with your actual domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:4173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response schemas ────────────────────────────────────────────────

class ChatRequest(BaseModel):
    """Request body for the /chat endpoint."""
    message: str


class ChatResponse(BaseModel):
    """Response body for the /chat endpoint."""
    response: str


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    """Health check route — confirms the API is running."""
    return {"message": "Portfolio Chatbot API is up and running! 🚀"}


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """
    Accept a user message and return a chatbot response.

    The response is generated by keyword matching logic in chatbot.py.
    """
    reply = get_response(request.message)
    return ChatResponse(response=reply)
